### PR TITLE
58 star notation fix

### PR DESCRIPTION
**Pull request by amorosej**
Fixed the constructor used for the star token feature so that the energy units are consistent and the level energy is not added to the electronic level (only to the formation enthalpy).

### CODE REVIEW

**Comment by jbscoggi** [comment]
This looks good.  What do you think about adding a test which checks that we retrieve a Boltzmann distribution of levels at equilibrium for a single species StS mixture?

**Comment by amorosej** [comment]
I have been thinking about that.

**Comment by jbscoggi** [comment]
Hey @amorosej, just wondering if you plan to add that test or not?  I think it would be better to do it before merging but if you don't have time, we can add it as an issue for later.

**Comment by amorosej** [comment]
Hi JB, I also think it would be nice to include the test before merging. Today I can't, but I will do it asap.

**Comment by jbscoggi** [comment]
OK great! No rush, I just wanted to make sure we were both on the same page.

**Comment by amorosej** [comment]
Hi, I added the test but the "continuous-integration/travis-ci" check seems frozen. Is it running ?

**Comment by jbscoggi** [comment]
Hey @amorosej, it seems all the tests passed but github didn't get the memo.  I manually restarted the tests on TravisCI.  Hopefully it will work this time.  If not I will try and figure out what to do.

**Comment by jbscoggi** [comment]
It seems the tests worked this time, merging.

**Pull request merged**
