### PR TITLE
WIP. Chemical production rate Jacobians.

### PR DESCRIPTION
**Pull request by grgbellasvki**
Work on Issue #74.
Still need to check Zeldovich reactions. 
Creating the pull request to see if the Segmentation fault I am getting is compiler specific.

### CODE REVIEW

**Comment by grgbellasvki** [comment]
The last commit in the master fixed the segmentation fault I was getting.

**Comment by grgbellasvki** [comment]
The tests seem to pass. A few comments about the bug.
It appeared when third body reactions where written as: A + B + C =  AB + C, where C was a "real" chemical species and not the thirdbody M. The fix was to check whether the products were inert during the reaction and prevent them from being add to the jacobian twice. Note that this bug was unlikely to have affected any simulations with the Park air-5, air-11 or air-carbon mixture.

The current solution can be improved by merging the two loops with the "if inert"  into a single one in JacobianManager.cpp file. 

This pull request will add the  (nu_i''- nu_i) (kf/dT * Pi [X_i]^nu_i'  - kb/dT * Pi [X_i]^nu_i'') jacobians soon.

**Comment by grgbellasvki** [comment]
Update: Segmentation fault still active. It seems it is associated to the deallocation of a pointer.

**Comment by jbscoggi** [comment]
Hey @grgbellasvki, can you provide a minimal working example for the segfault to issue #74?

**Comment by grgbellasvki** [comment]
There is a unit test (test_wdot_jacobians.cpp)  which passes in my system, but fails in linux.
There is no segfault if you do not call jacobiansRhoi.
Do you need something beyond that?

**Comment by jbscoggi** [comment]
No I guess that will be fine.  I was thinking about trying to reproduce the segfault.

**Comment by jbscoggi** [comment]
Hey @grgbellasvki, this seems like a WIP, can you let me know when you are "done" and then I will do the review.  Thanks.

**Comment by jbscoggi** [comment]
Hey @grgbellasvki, I'm going to close this PR in favor of the new one, #96, as per our discussion yesterday.

**Pull request closed without merging**
