### PR TITLE
Closing #114 mppshock

### PR DESCRIPTION
**Pull request by grgbellasvki**
Merge request in response to issue #114. Submitted in order to have the code reviewed.
The code is working, but testing still needed.

### CODE REVIEW

**Comment by rubendibattista** [comment]
I can comment on the cmake stuff, and it looks ok to me. Thanks for fixing the leftover white spaces. 

PS: I think you need to rebase this branch over the last commit on `master`

**Comment by jbscoggi** [comment]
Hey @grgbellas, I think this PR might have gotten lost in the wind a little but it seems nearly ready to merge.  Could you take care of removing `using namespace std`?  I think that's the only outstanding issue.  It would be great to have this capability finally shipped with M++!

**Comment by grgbellasvki** [comment]
Sounds good @jbscoggi. Let's spend 5 minutes during the next M++ meeting to discuss about unit testing of the new feature. As you know, we have implemented shocking so many times outside of Mutation to have a certain level of confidence on the results, but a simple comparison with CEA would be great. 

I think the latest push doesn't have `using namespace std;` anymore. Can you verify that this is the case. Honestly, looking at the code 1 year after it was implemented, I would modify/modernize a few parts of mppshock.cpp, but this is of lower priority. It would be very interested in a "strict" code review from your side, if you have the time/patience.

**Review by jbscoggi — APPROVED** [review]

**Comment by jbscoggi** [comment]
Hey @grgbellas yes it seems the latest push is good to go.  I will go ahead and merge.  We can discuss the validation testing during the meeting.  Would you mind to prepare a very small demo?  Maybe also a single slide with the equations/assumptions behind the code?

**Pull request merged**
