### PR TITLE
Fortran wrapper access to heavyThermalDiffusionRatios

### PR DESCRIPTION
**Pull request by ChiaraAmato**
I have implemented the function "heavyThermalDiffusionRatios" in both cwrapper.h and cwrapper.cpp following the function "frozenThermalConductivity". However, when I run a testcase using N2 and O2, I received that the Thermal diffusion ratios are zero for both species. Furthermore, can you confirm that the "heavyThermalDiffusionRatios" function is evaluating the coefficients for the temperature term in the diffusive velocities for the Stefan-Maxwell equation?

### CODE REVIEW

**Comment by rubendibattista** [comment]
Ehi @ChiaraAmato, I don't see any changes wrt our `master` branch. 

Did you commit and push your changes to your own fork?

**Comment by ChiaraAmato** [comment]
I thought I did. I am having trouble committing and pushing from the terminal. I don't know why it doesn't show me the changes here. Therefore, I added the files manually but I think those are just committed. I am figuring out why is not working. I will create a new pull request as soon as I fix it.

**Comment by ChiaraAmato** [comment]
Ok, I think I push them now. I can see the difference between my cwrapper.cpp and chapter.h. Can you confirm me that everything is ok now?
Thanks

**Comment by jbscoggi** [comment]
Hi @ChiaraAmato, could you please do a merge with the latest version of the master branch in your fork and then recommit?  It seems your changes will actually revert the copyright statements, which indicates you are not up to date with the latest version.  Here are some instructions if you need help: https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/syncing-a-fork.

**Comment by ChiaraAmato** [comment]
Ok, I will. I am sorry for the inconvenience

**Comment by jbscoggi** [comment]
No problem!  We are very happy that you are contributing! :)

**Comment by ChiaraAmato** [comment]
Ok, I created a new pull request. It was easier this way. Can you please let me know if this time I have done everything properly? Thank you.

**Comment by jbscoggi** [comment]
Closing this in favor of #123.

**Pull request closed without merging**
