### PR TITLE
fixed_irreversible_reactions_kb_computation

### PR DESCRIPTION
**Pull request by amorosej**
To verify it quickly, you may run " mppequil -m 0 -r 0,1 air5 " for a mechanism file with several reversible reactions (e.g. N2+M=2N+M), then rerun with one reaction made irreversible (e.g. N2+M=>2N+M). The results should be identical except for that irreversible reaction (kb should be equal to 0).

### CODE REVIEW

**Comment by jbscoggi** [comment]
Hey @amorosej, can you please add some tests to make sure that irreversible reactions are actually tested?  I think the reason the test coverage has dropped is because you have added new lines which never get run during testing.  See the code coverage report details for more specifics.

**Comment by jbscoggi** [comment]
After a little thought, you could probably just modify `test_reaction_mechanism.cpp`.  Note that the TestMechanism class already has an option to create a mechanism with irreversible reactions, so this should be pretty easy to add.  Just put the main TEST code into a function which takes as argument a `bool reversible` and then call it twice, once with `true`, the other with `false`.

**Comment by jbscoggi** [comment]
Hey @amorosej, there is something a little strange with the tests because one is not passing (take a look at the Details link next to the Travis CI stuff).  Can you investigate this?

**Comment by amorosej** [comment]
It says a test has not been run in the "release" version using g++-6.
"41/46 Test #42: example_equilibrium_air_run ...................................***Not Run   0.00 sec"
What does "not run" means ? 
I don't see the link with example_equilibrium_air_run which is not computing chemistry.

**Comment by jbscoggi** [comment]
I see what is going on now... we are running the tests in parallel and there are two tests associated with each example: one to compile and one to run.  The problem occurs because for whatever reason, the the test to run was called before compiling that example.  This is obviously a bug in the testing.  I will see what we can do and come back to you.

**Comment by jbscoggi** [comment]
OK, I have added a new PR (#57) which should fix this problem.  If that passes the tests I will merge it, which should fix the tests here.

**Pull request merged**
