### PR TITLE
Fix travis stuff

### LINKED ISSUE #84: make docs doesn't work
Since a recent PR, the Doxygen build is broken.

### PR DESCRIPTION
**Pull request by rubendibattista**
Fix #84 

I also added new compilers.

### CODE REVIEW

**Comment by jbscoggi** [comment]
It seems the new compilers didn't work, but you did fix the old ones...

**Comment by jbscoggi** [comment]
What I don't understand is how this broke in the first place, AFAICT the travis config file didn't change before this error occurred.  None of the other PRs open at the moment make changes to the travis file, and the previously merged PRs passed the tests.  Weird...

**Comment by rubendibattista** [comment]
The problem is in the way Travis does things. I guess before it was getting something by default, now they changed something, somehow removing that default...

I'll try to fix the others...

**Comment by rubendibattista** [comment]
btw Gitlab CI is way more clear...

**Comment by jbscoggi** [comment]
OK looks that's working, thanks!

**Pull request merged**
