### PR TITLE
Update electron molecular weight.

### LINKED ISSUE #210: Electron mass lacks precision
The electron mass defined as 5.5e-4 g/mol [here](https://github.com/mutationpp/Mutationpp/blob/d37d3c8f808ff356ce75235355aa8c7f8b77cf29/data/thermo/elements.xml#L5) in `elements.xml` is lacking in precision. The value defined [in the NASA-9 thermodynamics database](https://github.com/mutationpp/Mutationpp/blob/d37d3c8f808ff356ce75235355aa8c7f8b77cf29/data/thermo/nasa9.dat#L167) is 5.48579903e-4 g/mol, which agrees well with [NIST CODATA value](https://physics.nist.gov/cgi-bin/cuu/Value?mme|search_for=electron) of 5.4857990888e-4 g/mol.

Is there some reason that 5.5e-4 g/mol was used rather than a more precise value? If not, can I update this to use the value, either to match the NASA-9 value or the more recent CODATA value? This is causing issues when moving between Mutation++ and another code which is using the more precise NASA-9 electron mass for other calculations.

### PR DESCRIPTION
**Pull request by mgoodson-cvd**
Closes #210. Updates the electron molecular weight to be more precise. Uses the value given by the NASA-9 thermodynamics database.
Also updates the unit tests with the same value.

Fixes a minor bug with an undefined return type in XMLite.

Marking as draft because the `comparisonTest` unit test is still failing due to the use of old data. The comparison data will either need to be regenerated or the tolerance increased.

### CODE REVIEW

**Comment by jbscoggi** [comment]
Hey @mgoodson-cvd, It seems like some regression tests are failing, likely due to the change in the the electron molecular weight.  We just need to update the regression tests to use the new molecular weight value.  I'll come back to you with the procedure for doing this as soon as I remember how!

**Comment by jbscoggi** [comment]
@capriatim, I think you fixed the electron molecular weight in the past for US3D, can you check if this change is consistent with yours?

**Comment by mgoodson-cvd** [comment]
@jbscoggi I went digging and found @capriatim's commit [here](https://github.com/mutationpp/Mutationpp/commit/2fad1e34217e8b8ad3c44e47ca42071807a883a3). Our updated values for the electron molecular weight actually do match. @capriatim also updated the molecular weight of carbon; I am happy to tack that on to this PR, or we can leave it for a separate issue.

**Comment by mgoodson-cvd** [comment]
@jbscoggi Did you ever find your tool to generate the comparison unit test data? If it's long gone I can try to reverse-engineer it.

**Comment by mgoodson-cvd** [comment]
@jbscoggi I found the [`update_comparison` code](https://github.com/mutationpp/Mutationpp/blob/4cb6e3a05c15f49ffd346dc9f185ccc3459728b0/tests/c%2B%2B/update_comparison.cpp) and figured out how to use it to update the comparison data for the unit tests. I've added those and force pushed.

I also went ahead and updated the version number because this will cause users' answers to change.

**Comment by mgoodson-cvd** [comment]
Also, the unit test failures don't look to be my fault. Because you're using ubuntu-latest for the CI/CD, clang++ has updated recently and variable-length arrays (which you use in M++) now cause build errors.

**Comment by mgoodson-cvd** [comment]
Correction: the compiler error due to variable length arrays is coming from Catch, not Mutation++. I've replicated the ubuntu-latest build environment with clang 14, working off Mutation++ master branch. I'll see if simply updating Catch will solve this.

**Comment by mgoodson-cvd** [comment]
Closes #229. The `ubuntu-latest` builds are all successful after updating catch2.

Closes #230. The python 3.11 build is successful after updating pybind11.

Looks like your runners aren't picking up the `ubuntu-18.04` builds. I would consider dropping those and just using `ubuntu-latest`, at which point this PR will be good to go.

**Pull request merged**
