### PR TITLE
Add ability to set the GSI mechanism in MixtureOptions.

### LINKED ISSUE #180: Add setGSIMechanism to MixtureOptions
The `MixtureOptions` class has getters and setters for all its object strings (thermo_db, viscosity algorithm, etc) except that it is lacking a setter for the GSI Mechanism `m_gsi_mechanism`. There is a getter, [`getGSIMechanism`](https://github.com/mutationpp/Mutationpp/blob/c2e1ba718368597ebb9f3be0184f22061b8f6030/src/general/MixtureOptions.h#L218) so this appears to be an oversight.

I need this function so I have modified the code locally, but it would be nice to get this merged upstream. This is a very simple addition; I'll make the PR.

### PR DESCRIPTION
**Pull request by mgoodson-cvd**
Add the ability to set the GSI mechanism in the MixtureOptions
class.

See #180. Closes #180.

### CODE REVIEW

**Comment by mgoodson-cvd** [comment]
Rebased on latest master and force-pushed

**Review by jbscoggi — APPROVED** [review]
Seems fine to me!

**Comment by mgoodson-cvd** [comment]
@jbscoggi Thanks for approving. Anything else needed before you merge?

**Comment by jbscoggi** [comment]
Hey @mgoodson-cvd, sorry I was waiting for the testing stuff to be fixed but forgot to come back and hit the button!

**Pull request merged**
