### PR TITLE
added instructions to build local python package

### PR DESCRIPTION
**Pull request by ggange**

### CODE REVIEW

**Comment by Fratorhe** [comment]
Hi, 

It can be much easier. Simply do: 
`pip install . `

If you get an error related to PEP517 update essential packages: 
`pip install --upgrade pip setuptools wheel
`

Best, 
Fran

**Comment by rdbisme** [comment]
As @Fratorhe said. Closing! :)

`pip install .` is enough.

As I have a bit of spare time I'll enable the push of the pre-compiled wheel to PyPi for super easy install.

**Comment by rdbisme** [comment]
Actually documenting what @Fratorhe said would be beneficial. :)

**Comment by ggange** [comment]
Hello @rdbisme, here are the updated instructions (I added a small remark regarding zsh on macOS, since it was object of another question!). Thank you (@Fratorhe to you too)!

**Comment by rdbisme** [comment]
Closing as stale. Feel free to re-open addressing the comments from me and @Fratorhe.

**Comment by ggange** [comment]
Hi @rdbisme, is there something missing in the installation.md that is preventing this merge? I should have included yours and @Fratorhe comments in the instructions...

**Comment by rdbisme** [comment]
> Hi @rdbisme, is there something missing in the installation.md that is preventing this merge? I should have included yours and @Fratorhe comments in the instructions...

The section `## Build Python package locally` is not correct. `pip install .` is enough. The rest of the information is redundant with what is in `pyproject.toml` and already taken into account by `pip install .`. 

So the information about installing the Python wrappers is just `Run pip install .` in the root of the repo.

**Comment by ggange** [comment]
ok, thanks! Like this? :)

**Pull request merged**
